[feat] 공지사항 탭 스타일 작성
suji-family/lost-test pull request #11
Opened 2024-06-27 09:56 UTC by otw03

공지사항 탭 디자인 작성

탭 클릭시 이벤트 추가

2024-06-27 10:25 UTC, otw03 commented
Tab.tsx 에서 Link 의 href 바꾼 이유는 찾아보니 저런 식으로도 된다 해서 바꿔봄

2024-06-28 01:05 UTC, ahnkwang7379 requested changes

2024-06-28 01:05 UTC, ahnkwang7379 commented on src/app/news/notice/_component/Tab.tsx
> +  }
점검 탭에서 새로고침하면 선택된 탭이 점검일까요 공지일까요

2024-06-28 08:11 UTC, otw03 commented
이런 짧은 코드는 map 사용해서 줄이는 건 굳이임? 뭐 더 추가될 일도 없으니까?

2024-06-28 08:48 UTC, ahnkwang7379 requested changes

2024-06-28 08:48 UTC, ahnkwang7379 commented on src/app/news/notice/page.tsx
> +      <Tab searchParams={{ type: type }} />
type={type}으로 내리고 Tab에서도 object로 받지말고  그냥 type만 받는게 좋을듯

2024-06-28 08:50 UTC, ahnkwang7379 commented
> 이런 짧은 코드는 map 사용해서 줄이는 건 굳이임? 뭐 더 추가될 일도 없으니까?

하면 좋을듯!

2024-06-29 05:33 UTC, ahnkwang7379 approved these changes

2024-06-29 05:35 UTC, merged