[feat] 캐릭터 검색페이지 및 캐릭터 정보페이지 추가
suji-family/lost-test pull request #17
Opened 2024-07-06 11:02 UTC by otw03

캐릭터 검색페이지 및 캐릭터 정보페이지 추가

검색페이지 리액트쿼리 안 쓰고 params 이용해서 캐릭터네임 넘겨줬는데 이래도 되나?

캐릭터 정보페이지에서 CharacterDetail 컴포넌트 만들어서 데이터 보여주는 거 분리했는데 이렇게 하는 게 나은지?
정확히는 데이터 패칭까지 저 컴포넌트에서 하는 게 나은지, 아니면 페이지에서 패칭하고 props 로 내려주는 게 나은지 여부

2024-07-06 11:06 UTC, ahnkwang7379 commented
1. 검색해서 페이지 넘어가는거니까 괜찮음
2. 분리한거 좋음. 거기에 suspense + 스켈레톤 조합으로 데이터 받아오기 전 보여줄거 해주면 좋았을듯

2024-07-06 11:09 UTC, ahnkwang7379 requested changes

2024-07-06 11:09 UTC, ahnkwang7379 commented on src/app/profile/_component/SearchForm.tsx
> +        <Input
input 말고 좀 더 명확하게 지어주면 좋을듯

2024-07-06 11:09 UTC, ahnkwang7379 commented on src/app/profile/page.tsx
> +    <div>
무의미한 div

2024-07-07 12:10 UTC, otw03 commented
캐릭터 정보 없을 때 보여줄 화면 이렇게 해도 됨?

`  if (!characterList) {
    return (
      <section>
        <h1>캐릭터 정보 페이지</h1>
        <p>{decodeURIComponent(characterName)} 캐릭터 정보가 없습니다.</p>
      </section>
    )
  }`

2024-07-07 12:28 UTC, ahnkwang7379 commented
> 캐릭터 정보 없을 때 보여줄 화면 이렇게 해도 됨?
> 
> ` if (!characterList) { return ( <section> <h1>캐릭터 정보 페이지</h1> <p>{decodeURIComponent(characterName)} 캐릭터 정보가 없습니다.</p> </section> ) }`

ㅇㅋ

2024-07-09 01:35 UTC, ahnkwang7379 commented on src/app/profile/_component/SearchForm.tsx
> +import SearchInput from './Input'
이름을 바꾼건 좋은데 원본 컴포넌트명도 되도록 맞춰주세요
혹은 저 컴포넌트를 ui쪽으로 빼서 공용으로 만들어서 input으로 쓰거나

2024-07-09 12:55 UTC, otw03 commented
![image](https://github.com/suji-family/lost-test/assets/86701873/f62bf899-d387-4e56-998b-5c3fd247ee24)

2024-07-09 12:55 UTC, otw03 commented
전투 정보실 스타일 추가

![image](https://github.com/suji-family/lost-test/assets/86701873/0da0bca4-5c63-43f8-925b-07ef6d4f57d4)

2024-07-15 14:01 UTC, otw03 commented
css 클래스의 포함 관계를 표현하려고 아래처럼 했는데 어떤 게 나은지?

```
.profileInfo {
    display: flex;
    flex-direction: column;
    margin-right: 20px;

    .levelInfo {
        margin-bottom: 10px;

        .levelInfoExpedition,
        .levelInfoItem {
            display: flex;
            justify-content: space-between;
        }
    }

    .levelInfo2 {
        margin-bottom: 10px;

        .levelInfoItemAvg,
        .levelInfoItemMax {
            display: flex;
            justify-content: space-between;
        }
    }

    .gameInfo {
        margin-bottom: 10px;

        .gameInfoTitle,
        .gameInfoGuild,
        .levelInfoPvp,
        .gameInfoTown {
            display: flex;
            justify-content: space-between;
        }
    }
}
```
위의 css를 보면 `margin-bottom: 10px;` 부분이나
```
            display: flex;
            justify-content: space-between;
```
부분에서 중복이 많음


아니면 아래가 나은지? 이런 건 스타일 차이임? 별로 중요하지 않나?

```
        .levelInfoExpedition,
        .levelInfoItem,
        .levelInfoItemAvg,
        .levelInfoItemMax,
        .gameInfoTitle,
        .gameInfoGuild,
        .levelInfoPvp,
        .gameInfoTown {
            display: flex;
            justify-content: space-between;
        }
```

2024-07-15 14:07 UTC, otw03 commented
![image](https://github.com/user-attachments/assets/8ad5af4c-f9d9-4540-bd73-556fbccf67f8)


![image](https://github.com/user-attachments/assets/1609755a-cc3c-4d7b-ab96-f4b00a26330c)

2024-07-15 14:14 UTC, ahnkwang7379 commented
[CSS방법론](https://velog.io/@hahan/CSS%EB%B0%A9%EB%B2%95%EB%A1%A0OOCSS-BEM-SMACSS)

이런 것도 있음.
프로젝트나 같이 하는 사람들과 의견 맞춰서 결정해야하는 것 중 하나

2024-07-15 14:21 UTC, ahnkwang7379 commented
헌데 지금 스타일은 그냥 margin-bottom: 10px을 일일히 넣기보단
상위 profileInfo 에 gap 10px을 주는게 맞을듯

2024-07-15 14:25 UTC, ahnkwang7379 commented on src/app/profile/_component/SearchForm.tsx
> +      let updatedSearch = [
let 금지

2024-07-16 07:39 UTC, ahnkwang7379 requested changes

2024-07-16 07:39 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterDetail.tsx
> +          <img src={CharacterImage} alt="CharacterImage" />
혹시 이부분에서 경고 안뜸?

2024-07-16 07:39 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterDetail.module.scss
> +.CharacterInfoContainer {
컨벤션맞춰줘요

2024-07-16 07:39 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterDetail.tsx
> +  const characterList: CharacterList = await getCharacterList(characterName)
CharacterList 요거 안줘도 될듯? 이미 api호출부분에서 CharacterList로 돌려준다고 해뒀으니

2024-07-16 07:39 UTC, ahnkwang7379 commented on src/app/profile/_component/SearchForm.tsx
> +      ].slice(0, 4)
코드가 조금 혼란스러운거같음.
메서드 체이닝으로 하는법을 공부해봐.

2024-07-16 07:39 UTC, ahnkwang7379 commented on src/app/profile/_component/RecentSearch.module.scss
> +}
여기도 대문자 -> 소문자로 컨벤션 맞춰줘유

2024-07-16 07:39 UTC, ahnkwang7379 commented on src/model/armories/characters.ts
> +export type CharacterList = { ArmoryProfile: ArmoryProfile }
이러면 리스트가 아니지 않나 싶은데.

그리고 {ArmoryProfile:ArmoryProfile} 보단 그냥 ArmoryProfile을 쓰는게 나을듯?

2024-07-16 13:36 UTC, ahnkwang7379 approved these changes

2024-07-16 14:13 UTC, merged