캐릭터 정보창 툴팁 추가 & 스타일
suji-family/lost-test pull request #27
Opened 2024-07-22 10:49 UTC by otw03

캐릭터 정보창 툴팁 추가 & 스타일

2024-07-22 10:56 UTC, otw03 commented
![image](https://github.com/user-attachments/assets/76406a0e-3fe6-4f7c-b842-4698c91cb757)

2024-07-24 08:01 UTC, ahnkwang7379 approved these changes

2024-07-24 08:01 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterTooltip.module.scss
> +}
요 값 _zIndex.module 파일에 정의해서 가져다 쓰는걸로 바꿔주세유

2024-07-24 08:03 UTC, ahnkwang7379 requested changes
아니다 이거 뭔가 잘못했다 잠시만

2024-07-24 08:11 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterTooltip.tsx
> +        html={`<ul>
`@deprecated — Use children or render instead ` 경고가 있네요

2024-07-24 08:26 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterDetailStat.tsx
> +      ))}
이렇게 되면 툴팁이 stats 배열 안에 갯수만큼 생김
툴팁을 밖에 꺼내서 하나만 두고 사용하는 방법이 하나 있음
https://react-tooltip.com/docs/examples/render 요고 참고해봐

2024-07-24 14:44 UTC, otw03 commented on src/app/profile/character/[characterName]/_component/CharacterTooltip.module.scss
> +}
이건 안 해도 되는 거지?

2024-07-24 14:49 UTC, ahnkwang7379 commented on src/app/profile/character/[characterName]/_component/CharacterTooltip.module.scss
> +}
하는게 좋지

2024-07-24 14:59 UTC, ahnkwang7379 approved these changes
lgtm

2024-07-25 13:48 UTC, merged